@extends('layouts.auth')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="card card-signin p-3 my-5">
                <div class="card-body">
					<img class="logo" src="{{ get_logo() }}">
					
					<h5 class="text-center py-4">{{ _lang('Two Factor Authentication') }}</h4> 
					
                    @if(Session::has('error'))
                        <div class="alert alert-danger text-center">
                            <strong>{{ session('error') }}</strong>
                        </div>
                    @endif

                    @if(Session::has('success'))
                        <div class="alert alert-success text-center">
                            <strong>{{ session('success') }}</strong>
                        </div>
                    @endif

                    @php $routeUrl = auth()->user()->user_type == 'superadmin' ? route('admin.2fa.verify') : route('2fa.verify', auth()->user()->tenant->slug); @endphp
					<form method="POST" class="form-signin" action="{{ $routeUrl }}" autocomplete="off">
                        @csrf

                        <div class="two-factor-alert">
                            <span class="text-primary fs-14">{{ _lang('Please enter the code generated by your mobile application or security key.') }}</span>
                        </div>      

                        <div class="form-group row">
                            <div class="col-md-12">
                                <input type="text" class="form-control{{ $errors->has('one_time_password') ? ' is-invalid' : '' }}" name="one_time_password" value="{{ old('one_time_password') }}" placeholder="{{ _lang('Authentication Code') }}" required autofocus>

                                @if ($errors->has('one_time_password'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('one_time_password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-primary btn-block">
                                    {{ _lang('Authenticate') }}
                                </button>						
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection