<?php $__env->startSection('content'); ?>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="card card-signin p-3 my-5">
                <div class="card-body">
					<img class="logo" src="<?php echo e(get_logo()); ?>">
					
					<h5 class="text-center py-4"><?php echo e(_lang('Two Factor Authentication')); ?></h4> 
					
                    <?php if(Session::has('error')): ?>
                        <div class="alert alert-danger text-center">
                            <strong><?php echo e(session('error')); ?></strong>
                        </div>
                    <?php endif; ?>

                    <?php if(Session::has('success')): ?>
                        <div class="alert alert-success text-center">
                            <strong><?php echo e(session('success')); ?></strong>
                        </div>
                    <?php endif; ?>

                    <?php $routeUrl = auth()->user()->user_type == 'superadmin' ? route('admin.2fa.verify') : route('2fa.verify', auth()->user()->tenant->slug); ?>
					<form method="POST" class="form-signin" action="<?php echo e($routeUrl); ?>" autocomplete="off">
                        <?php echo csrf_field(); ?>

                        <div class="two-factor-alert">
                            <span class="text-primary fs-14"><?php echo e(_lang('Please enter the code generated by your mobile application or security key.')); ?></span>
                        </div>      

                        <div class="form-group row">
                            <div class="col-md-12">
                                <input type="text" class="form-control<?php echo e($errors->has('one_time_password') ? ' is-invalid' : ''); ?>" name="one_time_password" value="<?php echo e(old('one_time_password')); ?>" placeholder="<?php echo e(_lang('Authentication Code')); ?>" required autofocus>

                                <?php if($errors->has('one_time_password')): ?>
                                    <span class="invalid-feedback">
                                        <strong><?php echo e($errors->first('one_time_password')); ?></strong>
                                    </span>
                                <?php endif; ?>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-primary btn-block">
                                    <?php echo e(_lang('Authenticate')); ?>

                                </button>						
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.auth', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /home/u554938499/domains/app.alphagrantmanagement.com.au/public_html/resources/views/auth/2fa.blade.php ENDPATH**/ ?>